# Configuracao para gateways distribuidos
services:
  gateway-norte:
    build:
      context: ${PWD}/gateway
      dockerfile: Dockerfile
    container_name: gateway-norte
    env_file: ../.env
    network_mode: "host"
  gateway-sul:
    build:
      context: ${PWD}/gateway
      dockerfile: Dockerfile
    container_name: gateway-sul
    env_file: ../.env
    network_mode: "host"
  gateway-leste:
    build:
      context: ${PWD}/gateway
      dockerfile: Dockerfile
    container_name: gateway-leste
    env_file: ../.env
    network_mode: "host"
  gateway-oeste:
    build:
      context: ${PWD}/gateway
      dockerfile: Dockerfile
    container_name: gateway-oeste
    env_file: ../.env
    network_mode: "host"
