# Configuracao dos beacons de localizacao
services:
  beacon-norte:
    build:
      context: ${PWD}/beacon
      dockerfile: Dockerfile
    container_name: beacon-norte
    env_file: ../.env
    network_mode: "host"
  beacon-sul:
    build:
      context: ${PWD}/beacon
      dockerfile: Dockerfile
    container_name: beacon-sul
    env_file: ../.env
    network_mode: "host"
  beacon-leste:
    build:
      context: ${PWD}/beacon
      dockerfile: Dockerfile
    container_name: beacon-leste
    env_file: ../.env
    network_mode: "host"
  beacon-oeste:
    build:
      context: ${PWD}/beacon
      dockerfile: Dockerfile
    container_name: beacon-oeste
    env_file: ../.env
    network_mode: "host"
