version: "3.9"
# Configuracao dos dispositivos moveis (drones)
services:
  drone-norte:
    build: .
    container_name: drone-norte
    env_file: ../.env
    environment:
      - MISSION_DURATION=${MISSION_DURATION}
    network_mode: "host"
    ports:
      - "10000:10000"
  drone-sul:
    build: .
    container_name: drone-sul
    env_file: ../.env
    environment:
      - MISSION_DURATION=${MISSION_DURATION}
    network_mode: "host"
    ports:
      - "10001:10001"
  drone-leste:
    build: .
    container_name: drone-leste
    env_file: ../.env
    environment:
      - MISSION_DURATION=${MISSION_DURATION}
    network_mode: "host"
    ports:
      - "10002:10002"
  drone-oeste:
    build: .
    container_name: drone-oeste
    env_file: ../.env
    environment:
      - MISSION_DURATION=${MISSION_DURATION}
    network_mode: "host"
    ports:
      - "10003:10003"
