# Configuracao dos dispositivos moveis (drones)
services:
  drone-norte:
    build:
      context: ${PWD}/device
      dockerfile: Dockerfile
    container_name: drone-norte
    env_file: ../.env
    network_mode: "host"
  drone-sul:
    build:
      context: ${PWD}/device
      dockerfile: Dockerfile
    container_name: drone-sul
    env_file: ../.env
    network_mode: "host"
  drone-leste:
    build:
      context: ${PWD}/device
      dockerfile: Dockerfile
    container_name: drone-leste
    env_file: ../.env
    network_mode: "host"
  drone-oeste:
    build:
      context: ${PWD}/device
      dockerfile: Dockerfile
    container_name: drone-oeste
    env_file: ../.env
    network_mode: "host"
